# Project
mod_version=0.4.1+mc1.21.1-neoforge
maven_group=com.pebbles_boon.metalrender
archives_base_name=complemetal

# Minecraft / NeoForge
minecraft_version=1.21.1
neoforge_version=21.1.252
sodium_version=mc1.21.1-0.6.13-neoforge
iris_version=1.8.12+1.21.1-neoforge
junit_version=5.13.4

# Gradle
org.gradle.jvmargs=-Xmx4G -Dfile.encoding=UTF-8
org.gradle.parallel=true
org.gradle.configuration-cache=false
