package com.pebbles_boon.metalrender.sodium.mixins;

import com.pebbles_boon.metalrender.MetalRenderClient;
import com.pebbles_boon.metalrender.render.MetalWorldRenderer;
import net.caffeinemc.mods.sodium.client.render.chunk.RenderSection;
import net.caffeinemc.mods.sodium.client.render.chunk.RenderSectionManager;
import net.caffeinemc.mods.sodium.client.render.chunk.data.BuiltSectionInfo;
import org.spongepowered.asm.mixin.Mixin;
import org.spongepowered.asm.mixin.injection.At;
import org.spongepowered.asm.mixin.injection.Inject;
import org.spongepowered.asm.mixin.injection.Redirect;
import org.spongepowered.asm.mixin.injection.callback.CallbackInfo;

/**
 * Synchronizes Complemetal's independent terrain mesher with Sodium 0.6.13.
 */
@Mixin(value = RenderSectionManager.class, remap = false)
public abstract class SodiumRenderSectionManagerMixin {
  /**
   * Mirror rebuild requests generated by Sodium's own section scheduler.
   */
  @Inject(method = "scheduleRebuild", at = @At("RETURN"), require = 0)
  private void metalrender$mirrorRebuildSchedule(
      int x, int y, int z, boolean important, CallbackInfo ci) {
    if (!MetalRenderClient.isEnabled()) {
      return;
    }

    MetalWorldRenderer worldRenderer = MetalRenderClient.getWorldRenderer();
    if (worldRenderer == null || !worldRenderer.isReady()) {
      return;
    }

    worldRenderer.scheduleSectionRebuild(x, y, z);
  }

  /**
   * Mirror the first successful Sodium section upload into Complemetal's
   * independent CPU mesher. Sodium 0.6.13 performs this through
   * RenderSection.setInfo(BuiltSectionInfo) inside updateSectionInfo().
   */
  @Redirect(
      method = "updateSectionInfo",
      at = @At(value = "INVOKE",
          target = "Lnet/caffeinemc/mods/sodium/client/render/chunk/RenderSection;setInfo(Lnet/caffeinemc/mods/sodium/client/render/chunk/data/BuiltSectionInfo;)Z"),
      require = 0)
  private boolean metalrender$mirrorSectionUpload(
      RenderSection section, BuiltSectionInfo info) {
    boolean wasBuilt = section.getFlags() != 0;
    boolean changed = section.setInfo(info);
    if (!changed) {
      return false;
    }

    boolean isBuilt = section.getFlags() != 0;
    if (!wasBuilt && isBuilt) {
      MetalWorldRenderer worldRenderer = MetalRenderClient.getWorldRenderer();
      if (worldRenderer != null && MetalRenderClient.isEnabled()
          && worldRenderer.isReady()) {
        worldRenderer.scheduleCompiledSectionRebuild(
            section.getChunkX(), section.getChunkY(), section.getChunkZ());
      }
    }

    return true;
  }
}
